---
on:
  push:
    tags:
      - "*"

# Help here: https://github.com/espressif/esp-idf-ci-action

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      binaries: ${{ steps.artifact-upload-step.outputs.artifact-id }}
      version: ${{ steps.copy-binaries-step.outputs.version }}
    strategy:
      matrix:
        PRESET: [lilygo-amoled, lilygo-amoled-plus, waveshare-amoled]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: release-v6.1
        command: idf.py --preset ${{ matrix.PRESET }} build
        target: esp32s3
        path: '.'
    - name: Copy binaries
      id: copy-binaries-step
      shell: bash
      run: >
        mkdir -p dist dist/${{ matrix.PRESET }}
        dist/${{ matrix.PRESET }}/bootloader
        dist/${{ matrix.PRESET }}/partition_table;
        cp bin-README dist/${{ matrix.PRESET }}/README;
        cp build/${{ matrix.PRESET }}/bootloader/bootloader.bin
        dist/${{ matrix.PRESET }}/bootloader/;
        cp build/${{ matrix.PRESET }}/partition_table/partition-table.bin
        dist/${{ matrix.PRESET }}/partition_table/;
        cp build/${{ matrix.PRESET }}/tinyecg.bin
        build/${{ matrix.PRESET }}/flash_args
        dist/${{ matrix.PRESET }}/;
        echo "version=${{ github.ref_name }}" >>"$GITHUB_OUTPUT"
    - name: Save as atrifact
      uses: actions/upload-artifact@v7
      id: artifact-upload-step
      with:
        name: built-firmwares-${{ matrix.PRESET }}
        path: dist/
        retention-days: 1


  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repo
      uses: actions/checkout@v5
    - name: Restore artifact
      uses: actions/download-artifact@v8
      with:
        pattern: built-firmwares-*
        # artifact-ids: ${{ needs.build.outputs.binaries }}
        merge-multiple: true
        path: dist
    - name: Upload build
      shell: bash
      run: >
        ls -lR;
        cd dist;
        zip -r tinyecg-${{ needs.build.outputs.version }}.zip * ;
        gh release create ${{ needs.build.outputs.version }}
        tinyecg-${{ needs.build.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
#    - name: Remove artifacts
#      shell: bash
#      run: >
#        gh api repos/$REPO_OWNER/$REPO_NAME/actions/artifacts/${{ needs.build.outputs.binaries }} -X DELETE
#      env:
#        GITHUB_TOKEN: ${{ github.TOKEN }}
